name: Wildlifeinprint
favicon: null
layout_spectrum: 0.782818101812154
typography_spectrum: 0.34267874248325825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.057409198954701424
  rhythmicContrast: 0.5
purpose: []
