name: Wildlifeinprint
favicon: null
layout_spectrum: 0.0143
typography_spectrum: 0.83136
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebe3ea'
    - '#2e373d'
    - '#ee974a'
    - '#627045'
    - '#d66748'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
